TopSpeed.Web/Models/ErrorViewModel.cs
namespace TopSpeed.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TopSpeed.Web/Controllers/ToursController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TopSpeed.Web.Models;

namespace TopSpeed.Web.Controllers
{
    public class ToursController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TopSpeed.Web/Controllers/TraviaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TopSpeed.Web.Models;

namespace TopSpeed.Web.Controllers
{
    public class TraviaController : Controller
    {
        private readonly ILogger<TraviaController> _logger;

        public TraviaController(ILogger<TraviaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Destinations()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TopSpeed.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TopSpeed.Web</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TopSpeed.Web.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- font awesome cdn link  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">-->
</head>
<body>
    <header class="header" data-aos="fade-down">

        <section class="flex">

            <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">Travia.</a>

            <nav class="navbar">
                <a asp-area="" asp-controller="Travia" asp-action="Index">home</a>
                <a asp-area="" asp-controller="Travia" asp-action="About">about</a>
                <a asp-area="" asp-controller="Tours" asp-action="Index">tours</a>
                <a asp-area="" asp-controller="Travia" asp-action="Destinations">destinations</a>
                <a asp-area="" asp-controller="Travia" asp-action="Contact">contact</a>
            </nav>

            <div id="menu-btn" class="fas fa-bars"></div>

        </section>

    </header>
       <main role="main" class="pb-3">
           @RenderBody()
       </main>
 
    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TopSpeed.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TopSpeed.Web/Views/Tours/Index.cshtml
@{
    ViewData["Title"] = "Tours";
}
<!-- tours section starts  -->

<div class="container tours">

    <h1 class="heading" data-aos="zoom-out">popular places</h1>

    <section class="grid">

        <div class="box" data-aos="fade-up">
            <div class="price"><i class="fas fa-dollar-sign"></i><span>1299</span></div>
            <img src="images/tour-img-1.webp" class="image" alt="">
            <h3 class="name">taj mahal</h3>
            <p class="address">agra, india</p>
            <a href="#" class="btn">send enquiry</a>
        </div>

        <div class="box" data-aos="fade-up">
            <p class="price"><i class="fas fa-dollar-sign"></i><span>1999</span></p>
            <img src="images/tour-img-2.webp" alt="" class="image">
            <h3 class="name">tokyo</h3>
            <p class="address">tokyo, japan</p>
            <a href="#" class="btn">send enquiry</a>
        </div>

        <div class="box" data-aos="fade-up">
            <p class="price"><i class="fas fa-dollar-sign"></i><span>3000</span></p>
            <img src="images/tour-img-3.webp" alt="" class="image">
            <h3 class="name">hawaii</h3>
            <p class="address">hawaii, united state</p>
            <a href="#" class="btn">send enquiry</a>
        </div>

        <div class="box" data-aos="fade-up">
            <p class="price"><i class="fas fa-dollar-sign"></i><span>1203</span></p>
            <img src="images/tour-img-4.webp" alt="" class="image">
            <h3 class="name">london</h3>
            <p class="address">england, U.K.</p>
            <a href="#" class="btn">send enquiry</a>
        </div>

        <div class="box" data-aos="fade-up">
            <p class="price"><i class="fas fa-dollar-sign"></i><span>1999</span></p>
            <img src="images/tour-img-5.webp" alt="" class="image">
            <h3 class="name">lotus temple</h3>
            <p class="address">new delhi, india</p>
            <a href="#" class="btn">send enquiry</a>
        </div>

        <div class="box" data-aos="fade-up">
            <p class="price"><i class="fas fa-dollar-sign"></i><span>1000</span></p>
            <img src="images/tour-img-6.webp" alt="" class="image">
            <h3 class="name">Arc de Triomphe</h3>
            <p class="address">Paris, France</p>
            <a href="#" class="btn">send enquiry</a>
        </div>

    </section>

</div>

<!-- tours section ends -->

TopSpeed.Web/Views/Travia/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!-- home section starts  -->

<div class="container home" data-aos="zoom-out">

    <section class="flex" data-aos="zoom-in" data-aos-delay="600">

        <form action="" method="post">
            <h3>search your tour</h3>
            <p>where to</p>
            <input type="text" name="location" required maxlength="50" placeholder="enter tour location" class="box">
            <p>when to</p>
            <input type="date" name="date" class="box" required>
            <p>how many</p>
            <input type="number" name="guests" min="1" max="10" maxlength="2" placeholder="number of guests" required class="box">
            <input type="submit" value="search tour" name="search" class="btn">
        </form>

    </section>

</div>

<!-- home section ends -->

TopSpeed.Web/Views/Travia/about.cshtml
@{
    ViewData["Title"] = "About";
}
<!-- about section starts  -->

<div class="container about">

    <h1 class="heading" data-aos="zoom-out">about us</h1>

    <section>

        <div class="details">
            <div class="box" data-aos="zoom-in">
                <h3>why choose us?</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptate accusantium repellat aliquam esse odit commodi est cumque perferendis rem veritatis minus aliquid delectus eligendi.</p>
                <a href="contact.html" class="btn">contact us</a>
            </div>
        </div>

        <div class="grid">

            <div class="box" data-aos="fade-up">
                <img src="~/images/about-img-1.svg" alt="">
                <h3>easy bookings</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maiores sed blanditiis.</p>
            </div>

            <div class="box" data-aos="fade-up">
                <img src="~/images/about-img-2.svg" alt="">
                <h3>travel world</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maiores sed blanditiis.</p>
            </div>

            <div class="box" data-aos="fade-up">
                <img src="~/images/about-img-3.svg" alt="">
                <h3>enjoy tours</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maiores sed blanditiis.</p>
            </div>

        </div>

    </section>

</div>

<!-- about section ends -->
<!-- reviews section starts  -->

<div class="container reviews">

    <h1 class="heading" data-aos="zoom-out">client's reviews</h1>

    <section class="grid">

        <div class="box" data-aos="zoom-in">
            <img src="~/images/pic-1.png" alt="">
            <h3>john deo</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde illo distinctio repellendus delectus dicta modi iure, quod numquam nesciunt aspernatur.</p>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>

        <div class="box" data-aos="zoom-in">
            <img src="~/images/pic-2.png" alt="">
            <h3>john deo</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde illo distinctio repellendus delectus dicta modi iure, quod numquam nesciunt aspernatur.</p>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>

        <div class="box" data-aos="zoom-in">
            <img src="~/images/pic-3.png" alt="">
            <h3>john deo</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde illo distinctio repellendus delectus dicta modi iure, quod numquam nesciunt aspernatur.</p>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>

        <div class="box" data-aos="zoom-in">
            <img src="~/images/pic-4.png" alt="">
            <h3>john deo</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde illo distinctio repellendus delectus dicta modi iure, quod numquam nesciunt aspernatur.</p>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>

        <div class="box" data-aos="zoom-in">
            <img src="~/images/pic-5.png" alt="">
            <h3>john deo</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde illo distinctio repellendus delectus dicta modi iure, quod numquam nesciunt aspernatur.</p>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>

        <div class="box" data-aos="zoom-in">
            <img src="~/images/pic-6.png" alt="">
            <h3>john deo</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde illo distinctio repellendus delectus dicta modi iure, quod numquam nesciunt aspernatur.</p>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>

    </section>

</div>

<!-- reviews section ends -->

TopSpeed.Web/Views/Travia/contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<!-- contact section starts  -->

<div class="container contact">

   <h1 class="heading" data-aos="zoom-out">contact us</h1>

   <section>

      <div class="row">

         <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15077.086614958938!2d72.83608960687518!3d19.13958260781318!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b63aceef0c69%3A0x2aa80cf2287dfa3b!2sJogeshwari%20West%2C%20Mumbai%2C%20Maharashtra%20400047!5e0!3m2!1sen!2sin!4v1672939645362!5m2!1sen!2sin" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" data-aos="flip-left"></iframe>

         <form action="" method="post" data-aos="flip-right">
            <h3>get in touch</h3>
            <input type="text" name="name" required maxlength="50" placeholder="enter your name" class="box">
            <input type="email" name="email" required maxlength="50" placeholder="enter your email" class="box">
            <input type="number" name="number" required maxlength="10" min="0" max="9999999999" placeholder="enter your number" class="box">
            <textarea name="message" class="box" required maxlength="1000" cols="30" rows="10"></textarea>
            <input type="submit" value="send message" name="send" class="btn">
         </form>

      </div>

      <div class="grid">

         <div class="box" data-aos="fade-up">
            <i class="fas fa-phone"></i>
            <h3>phone number</h3>
            <a href="tel:1234567890">+123-456-7890</a>
            <a href="tel:1112223333">+111-222-3333</a>
         </div>

         <div class="box" data-aos="fade-up">
            <i class="fas fa-envelope"></i>
            <h3>email address</h3>
            <a href="mailto:shaikhanas@gmail.com">shaikhanas@gmail.come</a>
            <a href="mailto:anasbhai@gmail.com">anasbhai@gmail.come</a>
         </div>

         <div class="box" data-aos="fade-up">
            <i class="fas fa-map-marker-alt"></i>
            <h3>office address</h3>
            <a href="#">flat no. 01, a-1, jogeshwari, mumbai, india - 400104</a>
         </div>

      </div>

      <div class="credit">
         &copy; copyright 2023 by <span>Travia</span> |all rights reserved!
      </div>

   </section>

</div>

<!-- contact section ends -->

TopSpeed.Web/Views/Travia/destinations.cshtml
@{
    ViewData["Title"] = "Destinations";
}

<!-- destinations section starts  -->

<div class="container destinations">

    <h1 class="heading" data-aos="zoom-out">destinations</h1>

    <section class="grid">

        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-1.jpg" alt="">
            <h3><span>istanbul</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-2.jpg" alt="">
            <h3><span>california</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-3.jpg" alt="">
            <h3><span>london</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-4.jpg" alt="">
            <h3><span>morocco</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-5.jpg" alt="">
            <h3><span>new york</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-6.jpg" alt="">
            <h3><span>paris</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-7.jpg" alt="">
            <h3><span>barcelona</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-8.jpg" alt="">
            <h3><span>sydney</span></h3>
        </div>
        <div class="box" data-aos="zoom-in">
            <img src="~/images/destination-9.jpg" alt="">
            <h3><span>tokyo</span></h3>
        </div>

    </section>

</div>

<!-- destinations section ends -->